### ISSUE TITLE
[KM registratie] Inline tabs met dropdown

### ISSUE THREAD

**Issue by Poenai** [Driveperfect/imitationgame#3]
Hoi Danny,

Als je naar index.html navigeert in het project dan zie je het gehele voorbeeld project. Onder het menuitem "UI labs" vind je een submenu "tabs and accordions".

Omdat er sprake is van km registratie van meerdere auto's, plaatsen we de tabel in tabbladen.
Meest praktische is te kiezen voor de inline tabs met dropdown.

Zou je in kilometerregistratie.php enkele tabbladen willen opnemen (de 1e 3 komen in tabs en de rest in dropdowns). Elke tabblad stelt een kenteken van een auto voor.

**Comment by Poenai** [comment]
Als aanvulling op bovenstaande:

-Koppel iedere tabblad aan een javascript functie 
-Bij het selecteren van een tabblad(kenteken) wordt dmv een ajax request de database gegevens( SELECT \* FROM auto WHERE kenteken = 'XXX-X-XX') opgehaald. 
-Deze gegevens worden geconvert in JSON formaat, eventueel (http://www.bin-co.com/php/scripts/sql2json/)
-Het gehele resultaat komt in een table van het type 'table export'

**Comment by danny-janse** [comment]
Goedeavond,

Zover heb ik het mogenlijk gemaakt dat iedere tabblad alle gegevens opvraagt via ajax. Hierin word de kenteken van de auto als GET waarde meegegeven. Vervolgens moet het php bestand alle gegevens die benodigt zijn ophalen uit de database en deze samen met het kenteken terugsturen in JSON formaat
vervolgens zorgt javascript ervoor dat alle gegevens in het tabel komen te staan.

Helaas zit er nog een klein foutje in die benoemt is in commit d34b201.

Todo:
- Layout van add en edit in een sub-view zetten
- Een ajax request naar de webserver sturen met de nieuwe waarden als er op save of delete wordt gedrukt.
- Columns van de table aanpassen.

**Comment by danny-janse** [comment]
Zojuist heb ik de bug in commit d34b201 verholpen.

**Comment by Poenai** [comment]
- Bij het exporteren, moet het kenteken meegenomen worden. Anders weet je niet bij welke auto de km's bijhoren. 
- Verwijderen van niet werkende exportfuncties(ppt,word,txt,png)
- Verwijder de kollommen "van-naar" en "duur".
-  Inzien van een rit (detailsweergave) (via een subview), pictogram (naast edit +del)
- In het scherm van "nieuwe rit" neem je 2 extra invulvelden op: "via" en "bezoekadres".
- Mogelijkheid om een route als standaard in te stellen (db)
- Standaard routes worden getoond middels een dropdown

Tableheader

```
Rit Datum   Begin KM         Einde KM   Van - Naar  Begintijd   Eindtijd    Duur      Soort rit Opties

1   10/12/2014  02505   02515   R'dam Centraal - R'dam Noord    13:00pm 14:00pm 1 uur, 0 min    ZKL
```

formulier toevoegen

```
Datum: 
Begin KM: 
Eind KM:
Vertrekadres: 
Aankomstadres:
via (optioneel):
Soort rit:   Prive   Zakelijk  Woon-Werk
Omrijroute inbegrepen (invoerveld standaard 0)
```

```
Per rit moet u de volgende gegevens vermelden:

de datum
de begin- en eindstand van de kilometerteller
het adres van vertrek en het aankomstadres. Als u vanaf uw werkadres naar een afspraak rijdt en daarna weer terug, schrijft u de aankomst- en vertrekadressen op van zowel de heen- als de terugreis
de route die u hebt gereden, als u niet de meest gebruikelijke route hebt genomen
of het een privérit is of een zakelijke rit
de privé-omrijkilometers als u tijdens dezelfde rit zakelijke kilometers en privékilometers rijdt
```
