### ISSUE TITLE
Km registratie Menu

### ISSUE THREAD

**Issue by Poenai** [Driveperfect/imitationgame#6]
Uit praktisch oogpunt heb ik het volgende bedacht:

Registratie > kilometer > "Toevoegen" hernoem je naar Registratie > kilometer > "Overzicht"  (de table export). 
En neem een nieuw submenu item op die je "Nieuw" noemt. Bij het klikken op toevoegen opent zich een nieuwe subview (met daarin de mogelijkheid om een nieuw rit toe te voegen)

**Comment by danny-janse** [comment]
Deze aanpassing heb ik zojuist gedaan, in de eerst volgende commit staat deze online.
