### ISSUE TITLE
Menu items toevoegen 

### ISSUE THREAD

**Issue by Poenai** [Driveperfect/imitationgame#7]
Vul het menu aan (menu.php) met de volgende items:
- Transactie (niveau 1)
  - Bankboek (niveau 2)
  - Kasboek (niveau 2)
- Verkoop (niveau 1)
  - Invoeren (niveau 2)
  - Overzicht (niveau 2)
- Inkoop (niveau 1)
  - Invoeren (niveau 2)
  - Overzicht (niveau 2)

**Comment by danny-janse** [comment]
De nieuwe menu.php staat nu online.
